config/routes.rb
Adminimal::Engine.routes.draw do
  get '/' => 'pages#dashboard'
  post '/batch' => 'batch#batch', as: :batch
  post '/sort' => 'batch#sort', as: :sort
end

app/models/adminimal/application_record.rb
module Adminimal
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/controllers/adminimal/application_controller.rb
module Adminimal
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
    before_filter :set_nav

    def set_nav
    	@nav = []
    	Adminimal::Engine.routes.routes.each do |r|
    		if r.defaults[:action] == 'index' && r.defaults[:menu] != false
    			@nav << r.name
    		end
    	end
    end
  end
end

app/controllers/adminimal/batch_controller.rb
require_dependency "adminimal/application_controller"

module Adminimal
  class BatchController < ApplicationController
  protect_from_forgery :except => [:batch, :sort]

    def sort
    model = params[:model].constantize
    ids = params[:ids]
    ids.each_with_index do |m,i|
     news = model.find(m)
     news.position = i
     news.save
    end
    render :text => "Record Updated"
    end

    def batch
    	model = params[:model].constantize
    	action = params[:batch]
    	ids = params[:ids].split(',')
    	model.where(:id => ids).each do |m|
        m.send action
      end
    end
  end
end

app/controllers/adminimal/default_controller.rb
require_dependency "adminimal/application_controller"

module Adminimal
  
  class DefaultController < ApplicationController

  before_action :set_element, only: [:show, :edit, :update, :destroy]
  before_action :set_attrs, only: [:new, :edit]
  prepend_before_action :set_names

  def set_names
    @model     = controller_name.classify.constantize
    @singular  = controller_name.singularize
    @modelSym  = @singular.to_sym
    @modelPath = controller_name.pluralize
    @human     = @singular.humanize.to_s.capitalize
    @keys      = @model.attribute_names
    @search_attributes = @model.try(:search_attributes) || nil
  end


  def index
    @q = @model.ransack(params[:q])
    if defined? @model.row_ordering
      @resources = @q.result(distinct: true).order(@model.row_ordering).paginate(page: params[:page])
    else
      @resources = @q.result(distinct: true).paginate(page: params[:page])
    end
    if defined? @model.row_schema
      @row_schema = @model.row_schema 
    else
      @row_schema = ['id']
    end
  end

  def show
  end

  def new
    @resource = @model.new
  end

  def edit
  end

  def create
    @resource = @model.new(element_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to eval("#{@modelPath}_path"), notice: "#{@human} was successfully created." }
        format.json { render action: 'show', status: :created, location: @element }
      else
        format.html { render action: 'new' }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @resource.update(element_params)
        format.html { redirect_to eval("#{@modelPath}_path"), notice: "#{@human} successfully updated." }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to @resource, notice: "#{@human} was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_element
      @resource = @model.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def element_params
      params.require(@modelSym).permit!
    end

    def set_attrs
       if defined? @model.form_schema
          @attrs = @model.form_schema
       else 
          @attrs = []
          @model.attribute_names.each do |a|
            unless a == 'id' || a == 'created_at' || a == 'updated_at'
              fields = { :field => a }
              @attrs << fields
            end
          end
        end
         

    end
end


end

app/controllers/adminimal/pages_controller.rb
require_dependency "adminimal/application_controller"

module Adminimal
  class PagesController < ApplicationController
    def dashboard
    end

    def batch

    end
  end
end

app/helpers/adminimal/application_helper.rb
module Adminimal
  module ApplicationHelper
 
  end
end

app/helpers/adminimal/pages_helper.rb
module Adminimal
  module PagesHelper
  end
end

app/views/adminimal/default/_form.html.erb
<%= semantic_form_for(@resource) do |f| %>
  <div class="">
  <% @attrs.each do |i| %>
  <div class="form-inputs">
  <% if @model.respond_to?('uploaders') && @model.uploaders.keys.include?(i[:field].to_sym) %>
  <%= f.input i[:field], :as => :file, :hint => f.object.send(i[:field]).present? \
    ? image_tag(f.object.send(i[:field]).url, class: 'thumb')
    : content_tag(:span, "nothing uploaded") %>
  <% else %>
  <%= f.input i[:field], i %>
  <% end %>
  </div>
  <% end %>
  </div>
  <div class="form-actions">
    <%= f.actions %>
  </div>
<% end %>

app/views/adminimal/default/edit.html.erb
<% if notice.present? %>
<p class="notice"><%= notice %></p>
<% end %>
<div class="row">
  <div class="column"><h3>Editing <%= t "admin.#{controller_name}" %></h3></div>
   <div class="column index-actions">
<%= link_to 'Back', eval("#{@modelPath}_path"), class: 'button button-small' %>
	
</div>
</div>
<%= render 'form', resource: @resource %>

app/views/adminimal/default/index.html.erb
<% if notice.present? %>
<p class="notice"><%= notice %></p>
<% end %>
   <div class="main-actions">
   
   <%= link_to 'New', eval("new_#{@singular}_path"), class: 'button button-small' %>
   <% (@batches || []).each do |b| %>
   <a href="<%= batch_path %>" class="js-batch batch button button-small button-outline disabled" data-model="<%= @model %>" data-batch="<%= b %>" data-ids=""><%= b.upcase %> SELECTED</a>
   <% end %>
  <a href="<%= batch_path %>" class="js-batch batch button button-small button-outline disabled" data-model="<%= @model %>" data-batch="delete" data-ids="">DELETE SELECTED</a>
  </div>
<div class="row row-wrap">
 
  <div class="column">
    <table>
  <thead>
    <tr>
      <th></th>
      <% @row_schema.each do |a| %>
      
           <th> <%= sort_link(@q, a.to_sym) %></th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="<%= 'sortable' if @model.column_names.include? 'position' %>" href="<%= sort_path %>" data-model="<%= @model %>">
    <% @resources.each do |resource| %>
      <tr data-id="<%= resource.id %>">
        <td class="selectable"><div class="box"></div></td>
         <% @row_schema.each do |a| %>
           <td><%= resource.send a %></td>
         <% end %>
        <td class="index-actions" colspan="3"><%= link_to raw('
<i class="fa fa-eye" aria-hidden="true"></i>'), eval("#{@singular}_path(resource)"), class: 'button button-small' %>
       <%= link_to raw('<i class="fa fa-pencil-square" aria-hidden="true"></i>'), eval("edit_#{@singular}_path(resource)"), class: 'button button-small'  %>
       <%= link_to raw('<i class="fa fa-trash" aria-hidden="true"></i>'), eval("#{@singular}_path(resource)"), method: "delete", data: { confirm: 'Are you sure?' }, class: 'button button-small button-outline'  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= will_paginate @resources %>
  </div>

  
    <% if @search_attributes.present? %>
   <div class="column column-25 sidebar">
    <%= search_form_for @q do |f| %>
      <% @search_attributes.each do |a| %>
      <%= f.label a %>
      <% if @model.reflections.collect{|a, b| b.class_name if b.macro==:belongs_to}.compact.include?(a.to_s.split('_').first(a.to_s.split('_').size - 2).join("_").camelize) %>
        <%= f.collection_select a, a.to_s.split('_').first(a.to_s.split('_').size - 2).join("_").camelize.constantize.all, :id, :search_name, include_blank: true %>
      <% else %>
        <%= f.search_field a %>
      <% end %>
      <% end %>
      <div class="f-actions">
        <%= f.submit 'Search', :class => 'button-small' %>
        <% if params[:q].present? %>
        <%= link_to 'Reset', eval("#{@modelPath}_path"), class: 'button button-small button-outline' %>
        <% end %>
      </div>
    <% end %>
  </div>
     <% end %>
</div>

app/views/adminimal/default/new.html.erb
<% if notice.present? %>
<p class="notice"><%= notice %></p>
<% end %>
<div class="row">
  <div class="column"><h3>New <%= t "admin.#{controller_name}" %></h3></div>
   <div class="column index-actions">
<%= link_to 'Back', eval("#{@modelPath}_path"), class: 'button button-small' %>
	
</div>
</div>
<%= render 'form', resource: @resource %>

app/views/adminimal/default/show.html.erb
<% if notice.present? %>
<p class="notice"><%= notice %></p>
<% end %>
<div class="row">
  <div class="column"><h3><%= t "admin.#{controller_name}" %></h3></div>
   <div class="column index-actions"><%= link_to 'Edit', eval("edit_#{@singular}_path(@resource)"), class: 'button button-small'  %>
<%= link_to 'Show all', eval("#{@modelPath}_path"), class: 'button button-small' %>
	
</div>
</div>
<table>
<% @resource.attribute_names.each do |a| %>
<tr>
	<td>
		<strong><%= a %></strong>
	</td>
	<td>
		<p><%= @resource.send a %></p>
	</td>
		

</tr>
<% end %>
</table>
</div>

app/views/adminimal/pages/dashboard.html.erb
<h1>Pages#dashboard</h1>
<p>Find me in app/views/adminimal/pages/dashboard.html.erb</p>

app/views/layouts/adminimal/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin</title>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href='https://fonts.googleapis.com/css?family=Roboto+Mono:400,100,100italic,300,300italic,400italic,500,700italic,500italic,700' rel='stylesheet' type='text/css'>

    <!-- Include Editor style. -->
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.3.5/css/froala_editor.min.css' rel='stylesheet' type='text/css' />
<link href='https://cdnjs.cloudflare.com/ajax/libs/froala-editor/2.3.5/css/froala_style.min.css' rel='stylesheet' type='text/css' />

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'adminimal/application', media: 'all' %>
  </head>

  <body>
  	<header>
    <div class="container">
      <ul>
       <li><%= link_to 'dashboard', '/admin', class: 'button button-outline' %></li>
       <% @nav.each do |n| %>
       <li><%= link_to t("admin.#{n}"), eval("#{n}_path"), :class => (current_page?(eval("#{n}_path")) ? "active" : "")  %></li>
       <% end %>
      </ul>
    </div>
  		
  	</header>
	<div class="container clear_header">
    	<%= yield %>	
	</div>
	<footer>
 
<!-- Include JS file. -->
<%= javascript_include_tag 'adminimal/application' %>
 <script src="//cdn.ckeditor.com/4.6.0/full/ckeditor.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ckeditor/4.6.0/adapters/jquery.js"></script>  

    
	</footer>
  </body>
</html>